name: Ready the code and deploy

on: 
  push:
    branches:
      - 'main'

jobs:
  # job-1
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: copying the codes
        uses: actions/checkout@v4

      - name: install node-js
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0

      - name: check node version
        run: node -v

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: run the tests
        run: yarn test

  # job-2
  build-code:
    runs-on: ubuntu-latest
    needs: test-code
    steps:
      - name: install node-js
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0

      - name: copying the codes
        uses: actions/checkout@v4

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: build the codes
        run: yarn test

  # job-3
  deploy-code:
    runs-on: ubuntu-latest
    needs: build-code
    steps:
      - name: Deploy the codes
        run: echo "deploying...."
